#!/usr/bin/env python3
"""
Improved convert.py for mpv-lua-stubs.

Generates Lua Language Server stub files from mpv's Lua API documentation
(converted from RST to Markdown via Pandoc).

Changes from original:
  - Type inference: @param types are guessed from parameter names + descriptions
  - Return types: @return annotations are generated from description text
  - @class definitions: timer, overlay, hook objects get proper type definitions
  - Deduplication: repeated function definitions are merged
  - Better comment formatting: cleaner docstrings
  - More robust param parsing: handles optional params, varargs, union types
  - Error handling: graceful failures with clear messages
"""

import re
import os
import sys

# ── Configuration ──────────────────────────────────────────────────────────────

# Input markdown file (generated by Pandoc from mpv's lua.rst)
LUA_MD = "lua.md"

# Output directory
LIBRARY_DIR = "library"

# ── Type inference maps ────────────────────────────────────────────────────────

# Heuristic: parameter name → likely Lua type
# Order matters: more specific names before generic ones
PARAM_TYPE_HINTS = {
    # string-ish
    "key_name": "string",
    "key_text": "string",
    "terminal_style": "string",
    "string": "string",
    "msg": "string",
    "key": "string",
    "name": "string",
    "text": "string",
    "path": "string",
    "level": "string",
    "format": "string",
    "str": "string",
    "message": "string",
    "style": "string",
    "prompt": "string",
    "identifier": "string",
    "default_text": "string",
    "history_path": "string",
    "anchor": "string",
    # function/callback
    "fn": "fun(...)",
    "callback": "fun(...)",
    "opened": "fun()",
    "edited": "fun(string)",
    "submit": "fun(...)",
    "closed": "fun(string, integer)",
    "complete": "fun(string): table",
    "on_update": "fun(table)",
    # number
    "seconds": "number",
    "duration": "number",
    "priority": "number",
    "timeout": "number",
    "cursor_position": "integer",
    "max_size": "integer",
    "scale": "number",
    # boolean
    "keep_open": "boolean",
    "autoselect_completion": "boolean",
    "repeatable": "boolean",
    "scalable": "boolean",
    "complex": "boolean",
    "cancellable": "boolean",
    "playback_only": "boolean",
    "capture_stdout": "boolean",
    "allow_waits": "boolean",
    "allow_wait": "boolean",
    "disabled": "boolean",
    # table
    "table": "table",
    "flags": "table",
    "def": "any",
    "t": "any",
    "value": "any",
    "v": "any",
    "data": "any",
    "result": "any",
    "type": "string",
    "error": "string",
    "filter": "string",
    "log": "table",
    "items": "table",
    "args": "table",
    "p1": "string",
    "p2": "string",
}

# Patterns to extract return type from description text (first match wins)
RETURN_PATTERNS = [
    # Explicit return descriptions
    (r"(?i)returns\s+`nil,\s*error`", "nil, string"),
    (r"(?i)returns\s+nil,\s*error", "nil, string"),
    (r"(?i)returns\s+`true`", "boolean"),
    (r"(?i)returns\s+(a\s+)?Boolean", "boolean"),
    (r"(?i)returns\s+(the\s+)?string", "string"),
    (r"(?i)returns\s+(a\s+)?string", "string"),
    (r"(?i)returns\s+(a\s+)?number", "number"),
    (r"(?i)returns\s+(a\s+)?result\s+table", "table"),
    (r"(?i)returns\s+(a\s+)?table", "table"),
    (r"(?i)returns\s+(the\s+)?value", "any"),
    (r"(?i)returns\s+(a\s+)?value", "any"),
    (r"(?i)return\s+the\s+value\s+as\s+string", "string"),
    (r"(?i)return\s+the\s+property\s+value\s+as\s+Boolean", "boolean"),
    (r"(?i)return\s+the\s+property\s+value\s+as\s+number", "number"),
    (r"(?i)return\s+the\s+relative\s+time\s+in\s+seconds", "number"),
    (r"(?i)returns\s+the\s+process\s+ID", "integer"),
    # "Return a tuple of ..." patterns (multi-return)
    (r"(?i)returns?\s+a\s+tuple\s+of\s+(.*?)(?:\.|,)", None),  # handled specially
]

# Special functions with known return types (overrides heuristics)
KNOWN_RETURNS = {
    "mp.get_property": ("string|nil", "nil, string"),
    "mp.get_property_osd": ("string", "nil, string"),
    "mp.get_property_bool": ("boolean|nil", "nil, string"),
    "mp.get_property_number": ("number|nil", "nil, string"),
    "mp.get_property_native": ("any", "nil, string"),
    "mp.set_property": ("boolean|nil", "nil, string"),
    "mp.set_property_bool": ("boolean|nil", "nil, string"),
    "mp.set_property_number": ("boolean|nil", "nil, string"),
    "mp.set_property_native": ("boolean|nil", "nil, string"),
    "mp.del_property": ("boolean|nil", "nil, string"),
    "mp.command": ("boolean|nil", "nil, string"),
    "mp.get_time": ("number",),
    "mp.get_script_name": ("string",),
    "mp.get_opt": ("string|nil",),
    "mp.get_next_timeout": ("number|nil",),
    "mp.get_osd_size": ("number, number, number",),
    "mp.add_timeout": ("mp.timer",),
    "mp.add_periodic_timer": ("mp.timer",),
    "mp.create_osd_overlay": ("mp.overlay",),
    "mp.get_wakeup_pipe": ("integer",),
    "mp.register_event": ("boolean",),
    "mp.add_key_binding": ("nil",),
    "mp.add_forced_key_binding": ("nil",),
    "mp.command_native": ("table|nil", "nil, string"),
    "mp.commandv": ("boolean|nil", "nil, string"),
    "mp.command_native_async": ("table|nil", "nil, string"),
    "mp.abort_async_command": ("nil",),
    "mp.add_hook": ("nil",),
    "mp.osd_message": ("nil",),
    "mp.dispatch_events": ("nil",),
    "mp.get_script_directory": ("string|nil",),
    "utils.getcwd": ("string|nil", "nil, string"),
    "utils.readdir": ("table|nil", "nil, string"),
    "utils.file_info": ("table|nil", "nil, string"),
    "utils.split_path": ("string, string",),
    "utils.join_path": ("string",),
    "utils.subprocess": ("table",),
    "utils.subprocess_detached": ("nil",),
    "utils.getpid": ("integer",),
    "utils.get_env_list": ("table",),
    "utils.parse_json": ("table|nil", "nil, string"),
    "utils.format_json": ("string|nil", "nil, string"),
    "utils.to_string": ("string",),
    "utils.getcwd": ("string",),
}

# Known param types for specific functions (overrides heuristics)
KNOWN_PARAMS = {
    "mp.command": {
        "string": "string",
    },
    "mp.add_hook": {
        "type": "string",
        "priority": "integer",
        "fn": "fun(hook: mp.hook)",
    },
    "mp.add_key_binding": {
        "key": "string|nil",
        "name_fn": "string|nil",
        "fn": "fun()|fun(table)",
        "flags": "table|nil",
    },
    "mp.add_forced_key_binding": {
        "key": "string|nil",
        "name_fn": "string|nil",
        "fn": "fun()|fun(table)",
        "flags": "table|nil",
    },
    "mp.observe_property": {
        "name": "string",
        "type": '"none"|"native"|"bool"|"string"|"number"|nil',
        "fn": "fun(name: string, value: any)",
    },
    "mp.register_event": {
        "name": "string",
        "fn": "fun(event: table)",
    },
    "msg.log": {
        "level": '"fatal"|"error"|"warn"|"info"|"v"|"debug"|"trace"',
    },
    "input.get": {
        "table": "table",
    },
}

# ── Module definitions ─────────────────────────────────────────────────────────

# Sections to skip (regex patterns)
SKIP_SECTION_PATTERNS = [
    r"^##\s+Example\s*$",
    r"^##\s+Script location\s*$",
    r"^##\s+Details on the script initialization and lifecycle\s*$",
]


class Module:
    """Represents a target stub module."""

    def __init__(self, name, keyword, path_append):
        self.name = name
        self.keyword = keyword  # regex to match heading
        self.path = os.path.join(LIBRARY_DIR, path_append)
        self.content_arr = []  # list of blocks (each block is list of lines)


modules = [
    Module("mp", "", "mp.lua"),
    Module("msg", r"^##\s+mp\.msg.*", "mp/msg.lua"),
    Module("options", r"^##\s+mp\.options.*", "mp/options.lua"),
    Module("utils", r"^##\s+mp\.utils.*", "mp/utils.lua"),
    Module("input", r"^##\s+mp\.input.*", "mp/input.lua"),
]

# ── Utility functions ──────────────────────────────────────────────────────────

# Functions that are documented as part of other functions (extracted by the
# code-regex split). We'll track seen ones to avoid duplicates.
_seen_funcs: set = set()


def reset_seen_funcs():
    _seen_funcs.clear()


def is_duplicate(func_name, params_str):
    """Check if a function with the same name and params was already output."""
    key = f"{func_name}({params_str})"
    if key in _seen_funcs:
        return True
    _seen_funcs.add(key)
    return False


def ensure_dir(path):
    os.makedirs(os.path.dirname(path), exist_ok=True)


def read_lines(path):
    try:
        with open(path, encoding="utf-8") as f:
            return f.readlines()
    except FileNotFoundError:
        print(f"❌ Error: {path} not found. Run pandoc first.", file=sys.stderr)
        sys.exit(1)


def is_skip_section(line):
    """Check if a heading line should be skipped (e.g. Example, Script location)."""
    for pat in SKIP_SECTION_PATTERNS:
        if re.match(pat, line):
            return True
    return False


def scan_indices(lines, regex):
    """Return indices of lines matching regex, excluding skip sections."""
    indices = []
    for i, line in enumerate(lines):
        if re.match(regex, line) and not is_skip_section(line):
            indices.append(i)
    return indices


def split_at_indices(lines, indices):
    """Split a list of lines at the given indices into sub-blocks."""
    if not indices:
        return [lines] if lines else []

    blocks = []
    if indices[0] > 0:
        blocks.append(lines[: indices[0]])

    ends = indices[1:] + [len(lines)]
    for start, end in zip(indices, ends):
        block = lines[start:end]
        if block:
            blocks.append(block)
    return blocks


def infer_param_type(param_name, params_str, desc_lines, base_name):
    """
    Infer the Lua type for a parameter.

    Priority:
    1. Known params for specific function
    2. Heuristic from parameter name
    3. 'any' as fallback
    """
    # Check known overrides for this function
    if base_name in KNOWN_PARAMS and param_name in KNOWN_PARAMS[base_name]:
        return KNOWN_PARAMS[base_name][param_name]

    # Check parameter name heuristics
    if param_name in PARAM_TYPE_HINTS:
        return PARAM_TYPE_HINTS[param_name]

    # Look for type hints in description lines
    for line in desc_lines:
        if re.search(rf"(?i)`{re.escape(param_name)}`\s+is\s+a\s+string", line):
            return "string"
        if re.search(rf"(?i)`{re.escape(param_name)}`\s+is\s+a\s+Boolean", line):
            return "boolean"
        if re.search(rf"(?i)`{re.escape(param_name)}`\s+is\s+(a\s+)?number", line):
            return "number"
        if re.search(rf"(?i)`{re.escape(param_name)}`\s+is\s+a\s+table", line):
            return "table"

    return "any"


def infer_return_type(desc_lines, base_name):
    """
    Infer return type annotations from description text.

    Returns list of @return annotation strings, or empty list.
    """
    # Check known returns first
    if base_name in KNOWN_RETURNS:
        types = KNOWN_RETURNS[base_name]
        if len(types) == 1:
            return [f"---@return {types[0]}"]
        else:
            returns = []
            for t in types:
                returns.append(f"---@return {t}")
            return returns

    desc = " ".join(desc_lines)

    for pattern, rtype in RETURN_PATTERNS:
        if re.search(pattern, desc):
            if rtype is None:
                # Special handling for "returns a tuple of ..."
                m = re.search(pattern, desc)
                if m:
                    parts = m.group(1)
                    # Try to extract @return for each tuple element
                    items = re.findall(r"[a-zA-Z0-9_]+", parts)
                    return [f"---@return {item}" for item in items]
                return []
            return [f"---@return {rtype}"]

    # Default: check for "On error, nil, error" pattern
    if re.search(r"(?i)on\s+error,?\s+`?nil`?,\s*`?error`?", desc):
        return ["---@return any|nil", '---@return nil|string']

    return []


def extract_params_and_overloads(func_line):
    """
    Extract parameter info and generate overload function signatures.

    Returns (base_name, params_info, overloads)
    - base_name: e.g. "mp.get_property"
    - params_info: list of dicts with keys: name, is_optional, inferred_type
    - overloads: list of "function xxx(...) end\\n" strings
    """
    m = re.match(r"`([a-zA-Z0-9_.]+)\((.*)\)`", func_line)
    if not m:
        return None, [], []

    base_name = m.group(1)
    params_str = m.group(2).strip()

    # Special case: no params
    if not params_str:
        return base_name, [], [f"function {base_name}() end\n"]

    # ── Parse parameters ──
    # Handle vararg (...)
    if params_str == "...":
        return base_name, [{"name": "...", "is_optional": False, "type": "any"}], [
            f"function {base_name}(...) end\n"
        ]

    # Extract param names, preserving optional markers
    param_names = _extract_param_names(params_str)

    params_info = []
    for pname, is_optional in param_names:
        params_info.append(
            {
                "name": pname,
                "is_optional": is_optional,
                "type": "any",  # filled in later with description context
            }
        )

    # ── Generate overloads ──
    overloads = []
    has_brackets = "[" in params_str
    has_union = "|" in params_str or "/" in params_str

    if has_brackets or has_union:
        # Full version: all params
        all_params = _clean_params_str(params_str)
        overloads.append(f"function {base_name}({all_params}) end\n")

        # Base version: strip optional params
        base_raw = re.sub(r"\[.*?\]", "", params_str)
        base_raw = base_raw.replace("|", "|").replace("/", "|")
        base_params = ", ".join(
            re.findall(r"[a-zA-Z0-9_]+", base_raw)
        )
        if base_params and base_params != all_params:
            overloads.append(f"function {base_name}({base_params}) end\n")
    else:
        overloads.append(f"function {base_name}({params_str}) end\n")

    return base_name, params_info, overloads


def _extract_param_names(params_str):
    """
    Extract parameter names from a params string like "str [, trail]" or "name, fn".

    Returns list of (name, is_optional) tuples.
    Handles:
      - Simple: "name, fn" → [("name", False), ("fn", False)]
      - Optional: "str [, trail]" → [("str", False), ("trail", True)]
      - Vararg: "..." → "..."
    """
    # Normalize: remove outer whitespace, collapse spaces
    s = params_str.strip()

    # Split on commas, respecting brackets
    parts = _split_params(s)

    result = []
    for part in parts:
        part = part.strip()
        if not part:
            continue

        # Check if entire part is optional (wrapped in [...])
        m = re.match(r"\[(.+)\]", part)
        if m:
            inner = m.group(1).strip()
            # Inside the brackets, extract the param name
            names = re.findall(r"[a-zA-Z0-9_]+", inner)
            if names:
                name = names[0]  # take the first name
                # Check if there's a default or type annotation like `trail`
                result.append((name, True))
            continue

        # Check for patterns like "name, [opt]" or "name, fn"
        # Just split on commas and process each
        sub_names = re.findall(r"[a-zA-Z0-9_]+", part)
        if sub_names:
            result.append((sub_names[0], False))

    return result


def _split_params(params_str):
    """Split params string on commas, respecting nested brackets."""
    parts = []
    depth = 0
    current = ""
    for ch in params_str:
        if ch == "[":
            depth += 1
            current += ch
        elif ch == "]":
            depth -= 1
            current += ch
        elif ch == "," and depth == 0:
            parts.append(current)
            current = ""
        else:
            current += ch
    if current:
        parts.append(current)
    return parts


def _clean_params_str(params_str):
    """Clean a params string for use as a function signature: normalize separators."""
    s = params_str.replace("|", "_").replace("/", "_")
    names = re.findall(r"[a-zA-Z0-9_]+", s)
    return ", ".join(names)


def clean_description_line(line):
    """Clean up a markdown description line for use as a Lua comment."""
    line = line.rstrip("\n")
    line = line.rstrip()
    return line


def _process_one_func(sb, code_regex):
    """
    Process a single sub-block containing a function signature and its docs.

    Returns a list of output lines, or None if the sub-block should be skipped.
    """
    first_line = sb[0]
    m = re.match(code_regex, first_line)
    if not m:
        return None

    func_line = first_line.strip()

    # Extract params and generate overloads
    base_name, params_info, overloads = extract_params_and_overloads(func_line)

    if base_name is None:
        return None

    # Skip duplicates (same function name + signature)
    sig_match = re.match(r"`[a-zA-Z0-9_.]+\((.*)\)`", func_line)
    params_raw = sig_match.group(1) if sig_match else ""
    if is_duplicate(base_name, params_raw):
        return None

    # Collect description lines
    desc_lines = [clean_description_line(line) for line in sb[1:]]

    # --- Generate @param annotations ---
    param_anns = []
    for info in params_info:
        pname = info["name"]
        inferred_type = infer_param_type(
            pname, params_raw, desc_lines + [func_line], base_name
        )
        opt_mark = "?" if info["is_optional"] else ""
        param_anns.append(f"---@param {pname}{opt_mark} {inferred_type}\n")

    # --- Generate @return annotations ---
    return_anns = infer_return_type(desc_lines, base_name)

    # --- Assemble ---
    # Format: description + @param + @return + overloads + blank line
    output = []
    for line in desc_lines:
        if line:
            output.append(f"-- {line}\n")
        else:
            output.append("--\n")
    output.extend(param_anns)
    output.extend(r + '\n' for r in return_anns)
    output.extend(overloads)
    output.append("\n")

    return output


def should_write_class_def(module_name):
    """Check if we should prepend @class definitions to this module."""
    return module_name == "mp"


def get_class_definitions():
    """Return @class definition blocks to prepend to mp.lua."""
    return [
        # --- mp.timer ---
        "---@class mp.timer\n",
        "---@field timeout number\n",
        "---@field oneshot boolean\n",
        "--- Disable the timer. Does nothing if already disabled.\n",
        '---@field stop fun()\n',
        "--- Disable the timer and reset elapsed time.\n",
        '---@field kill fun()\n',
        "--- Restart the timer.\n",
        '---@field resume fun()\n',
        "--- Whether the timer is currently enabled.\n",
        '---@field is_enabled fun(): boolean\n',
        "\n",
        # --- mp.overlay ---
        "---@class mp.overlay\n",
        "---@field data string\n",
        "---@field format string\n",
        "---@field id integer\n",
        "---@field z integer\n",
        "---@field w integer|nil\n",
        "---@field h integer|nil\n",
        "---@field ox integer\n",
        "---@field oy integer\n",
        "--- Commit the overlay to the screen.\n",
        '---@field update fun(): table\n',
        "--- Remove the overlay from the screen.\n",
        '---@field remove fun()\n',
        "\n",
        # --- mp.hook ---
        "---@class mp.hook\n",
        "--- Defer the hook continuation.\n",
        '---@field defer fun()\n',
        "--- Continue the hook.\n",
        '---@field cont fun()\n',
        "\n",
    ]


# ── Main pipeline ──────────────────────────────────────────────────────────────


def run_pipeline():
    print("🔧 Generating mpv Lua stubs...")
    ensure_dir(os.path.join(LIBRARY_DIR, "mp"))

    md_lines = read_lines(LUA_MD)

    # Step 1: Split by headings
    heading_indices = scan_indices(md_lines, r"^##.*")
    heading_blocks = split_at_indices(md_lines, heading_indices)

    # Step 2: Assign blocks to modules
    for block in heading_blocks:
        assigned = False
        for mod in modules[1:]:
            if mod.keyword and re.match(mod.keyword, block[0]):
                mod.content_arr.append(block)
                assigned = True
                break
        if not assigned:
            modules[0].content_arr.append(block)

    # Step 3: Process each module — split blocks into functions
    code_regex = r"^`[a-zA-Z0-9_.]+\(.*?\)`"

    for mod in modules:
        reset_seen_funcs()
        new_mod_blocks = []

        for block in mod.content_arr:
            # Find function signature lines in this block
            func_indices = scan_indices(block, code_regex)
            sub_blocks = split_at_indices(block, func_indices)

            processed_subs = []
            for sb in sub_blocks:
                if not sb:
                    continue

                first_line = sb[0]
                m = re.match(code_regex, first_line)

                if not m:
                    # Non-function content (e.g. intro paragraph) — skip
                    continue

                # Handle comma-separated function signatures on one line
                # e.g. `msg.fatal(...)`, `msg.error(...)`, ...
                all_func_sigs = re.findall(
                    r"`[a-zA-Z0-9_.]+\(\.\.\.\)`", first_line
                )
                if len(all_func_sigs) > 1:
                    # Split into multiple separate entries
                    for sig in all_func_sigs:
                        sb_copy = [sig + "\n"] + sb[1:]
                        result = _process_one_func(sb_copy, code_regex)
                        if result:
                            processed_subs.append(result)
                    continue

                result = _process_one_func(sb, code_regex)
                if result:
                    processed_subs.append(result)

            new_mod_blocks.append(processed_subs)

        mod.content_arr = new_mod_blocks

    # Step 4: Write output files
    for mod in modules:
        output_lines = ["---@meta\n"]

        if mod.name == "mp":
            output_lines.append("mp = mp\n\n")
            # Add class definitions
            output_lines.extend(get_class_definitions())
        else:
            output_lines.append(f"{mod.name} = {{}}\n\n")

        for block in mod.content_arr:
            for sub_block in block:
                output_lines.extend(sub_block)
            output_lines.append("\n")

        output_lines.append(f"return {mod.name}\n")

        try:
            with open(mod.path, "w", encoding="utf-8") as f:
                f.writelines(output_lines)
            print(f"  ✅ {mod.name} → {mod.path}")
        except IOError as e:
            print(f"  ❌ Failed to write {mod.path}: {e}", file=sys.stderr)
            sys.exit(1)

    print("🎉 Done!")


if __name__ == "__main__":
    run_pipeline()
